In [49]:
import numpy as np
import random
import matplotlib
import nnfs
import math
nnfs.init()

In [51]:
def f(x):
    y = 4*x + 2
    return y

In [4]:
inputs = [1 , 2, 5.4]
weights = [3.1, 2.1, 8.7]
bias = 3

output = 0

for i in range(len(inputs)):
    output += inputs[i] * weights[i]
output+=bias

In [5]:
print(output)

57.28


In [6]:
inputs = [1 , 2, 3, 2.5]
weights = [.2, .8, -.5, 1]
bias = 2

output = 0

for i in range(len(inputs)):
    output += inputs[i] * weights[i]
output+=bias
print(output)

4.8


In [11]:
inputs = [1 , 2, 3, 2.5]

weights = [[.2, .8, -.5, 1],
          [.5, -.91, .26, -.5],
          [-.26, -.27, .17, .87]]

biases = [2, 3, .5]

output1, output2, output3 = 0,0,0

for i in range(len(inputs)):
    output1 += inputs[i] * weights1[i]
output1+=bias1

for i in range(len(inputs)):
    output2 += inputs[i] * weights2[i]
output2+=bias2

for i in range(len(inputs)):
    output3 += inputs[i] * weights3[i]
output3+=bias3
output = [output1, output2, output3]
print(output)

[4.8, 1.21, 2.385]


In [13]:
inputs = [1 , 2, 3, 2.5]

weights = [[.2, .8, -.5, 1],
          [.5, -.91, .26, -.5],
          [-.26, -.27, .17, .87]]

biases = [2, 3, .5]

layer_outputs = []

for nueron_weights, nueron_bias in zip(weights, biases):
    neuron_output = 0
    for n_input, weight in zip(inputs, nueron_weights):
        neuron_output += n_input*weight
    neuron_output += nueron_bias
    layer_outputs.append(neuron_output)

print(layer_outputs)

[4.8, 1.21, 2.385]


In [15]:
np.dot(inputs,weights[0])+biases[0]

4.8

In [20]:
output = np.dot(weights, inputs) + biases

In [18]:
print(output)

[4.8, 1.21, 2.385]


In [30]:
inputs = [[1 , 2, 3, 2.5],
          [2, 5, -1, 2],
          [-1.5, 2.7, 3.3, -.8]]

weights1 = [[.2, .8, -.5, 1],
          [.5, -.91, .26, -.5],
          [-.26, -.27, .17, .87]]

biases1 = [2, 3, .5]


weights2 = [[.1, -.14, .5],
          [-.5, .12, -.33],
          [-.44, .73, -.13]]

biases2 = [-1, 2, -.5]

layer1_outputs = np.dot(inputs, np.array(weights1).T) + biases1
layer2_outputs = np.dot(layer1_outputs, np.array(weights2).T) + biases2

print(layer2_outputs)

[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]


In [42]:
np.random.seed(0)
X = [[1 , 2, 3, 2.5],
     [2, 5, -1, 2],
     [-1.5, 2.7, 3.3, -.8]]

In [43]:
class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = .1 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1,n_neurons)) 
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

In [44]:
layer1 = Layer_Dense(4, 5)
layer2 = Layer_Dense(5, 2)

In [45]:
layer1.forward(X)
print(layer1.output)

[[ 0.10758131  1.03983522  0.24462411  0.31821498  0.18851053]
 [-0.08349796  0.70846411  0.00293357  0.44701525  0.36360538]
 [-0.50763245  0.55688422  0.07987797 -0.34889573  0.04553042]]


In [46]:
layer2.forward(layer1.output)
print(layer2.output)

[[ 0.148296   -0.08397602]
 [ 0.14100315 -0.01340469]
 [ 0.20124979 -0.07290616]]


In [48]:
#RElU
inputs = [0,2,-1,3.3,-2.7,1.1,2.2,-100]
output = []

for i in inputs:
    output.append(max(0,i))
print(output)

[0, 2, 0, 3.3, 0, 1.1, 2.2, 0]


In [56]:
class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = .1 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1,n_neurons)) 
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

class Activation_ReLU:
    def forward(self, inputs):
        self.output = np.maximum(0,inputs)

In [64]:
X = np.array([[1 , 2, 3, 2.5],
     [2, 5, -1, 2],
     [-1.5, 2.7, 3.3, -.8]])

layer1 = Layer_Dense(4, 5)
activation1 = Activation_ReLU()
layer1.forward(X)
print(layer1.output)
activation1.forward(layer1.output)
print(activation1.output)


[[ 0.5657256  -0.11232398 -0.1293504  -0.06282973 -0.3650581 ]
 [ 0.36680803 -0.30675593 -0.8060944   0.5855212   0.02030431]
 [ 0.5520387  -0.39003506 -0.22158322  0.1292395  -0.07330865]]
[[0.5657256  0.         0.         0.         0.        ]
 [0.36680803 0.         0.         0.5855212  0.02030431]
 [0.5520387  0.         0.         0.1292395  0.        ]]


In [ ]:
class Activation_Softmax:
    def forward(self, inputs):
        exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
        probabilities = exp_values / np.sum(exp_values, axis=1, keepdims=True)
        self.output = probabilities

In [69]:
def f(x):
    y = 4*x + 2
    return y

In [70]:
class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = .1 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1,n_neurons)) 
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

class Activation_ReLU:
    def forward(self, inputs):
        self.output = np.maximum(0,inputs)
        
class Activation_Softmax:
    def forward(self, inputs):
        exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
        probabilities = exp_values / np.sum(exp_values, axis=1, keepdims=True)
        self.output = probabilities

In [75]:
X = np.random.rand(3,4)
print(X)
print()
for i in range(3):
    for j in range(4):
        X[i][j] = f(X[i][j])
    
print(X)

[[0.13248763 0.05342718 0.72559436 0.01142746]
 [0.77058075 0.14694665 0.07952208 0.08960303]
 [0.67204781 0.24536721 0.42053947 0.55736879]]

[[2.52995054 2.21370873 4.90237746 2.04570983]
 [5.08232299 2.58778658 2.31808833 2.35841214]
 [4.68819123 2.98146884 3.68215787 4.22947517]]


In [86]:
layer1 = Layer_Dense(4,5)
layer1.forward(np.array(X))
activation1 = Activation_ReLU()
activation1.forward(layer1.output)
layer2 = Layer_Dense(5,1)
activation2 = Activation_Softmax()
layer2.forward(activation1.output)
activation2.forward(layer2.output)
print(activation2.output)

[[1.]
 [1.]
 [1.]]
